### ISSUE TITLE
open edit byte in dark mode look like the image 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1367]
![image](https://github.com/manojnegi07/social-external/assets/81085431/0ddf46cd-8e6e-4a6e-b4d9-a4f426583252)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/9d366f76-765f-40a3-94c2-20fb6b7e535e)

not reflecting at my end

**Comment by vayuzpriya** [comment]
copy text form somewhere then check

**Comment by vayuzpriya** [comment]
Details / use case provided

**Comment by milivayuz** [comment]
https://github.com/manojnegi07/social-external/assets/156641922/20903c73-7063-48dc-b4e1-39ee33b7db9f

Edit button is not working

**Comment by manojnegi07** [comment]
It is working fine. Need to discuss

**Comment by manojnegi07** [comment]
Fixed. Please clear cache before checking

**Comment by rgnarok** [comment]
<img width="922" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/13076a28-142c-414b-adfe-df805ed38f57">

Not fixed

**Comment by manojnegi07** [comment]
Clear cache once before checking
